Config = {}

Config.RequireStill = true
Config.MaxMovement = 1.0

Config.DefaultVolume = 0.5
Config.AudioRange = 25.0

Config.EmoteResource = nil

Config.Freestyle = {
    enabled = false,
    tipMultiplier = 0.80
}

Config.NextSongPrompt = {
    enabled = true,
    title = 'Song finished',
    content = 'Play another song?',
    confirm = 'Yes',
    cancel = 'No'
}

Config.NPC = {
    enabled = true,
    radius = 22.0,
    maxReactingPeds = 30,
    scanInterval = 4500,
    approachTimeout = 24000,
    approachChance = 70,
    tipChance = 70,
    tipCooldownPerPed = 180000,
    notifyOnTip = true,

    voiceEnabled = true,
    voiceChance = 30,
    voiceSpeechParams = 'SPEECH_PARAMS_FORCE_NORMAL_CLEAR',

    oneReactionPerSession = true,

    leaveDistance = 16.0,
    leaveSpeed = 1.2,

    -- crowd / hang around
    lingerTime = { min = 25000, max = 60000 },
    reactionSpacing = { min = 2200, max = 4200 },
    watchRadius = 2.8,
    minApproachDistance = 4.0,

    positiveSpeech = {
        'GENERIC_CHEER',
        'GENERIC_HI',
        'GENERIC_AGREE',
        'GENERIC_THANKS'
    },

    positiveReactions = {
        { type = 'scenario', name = 'WORLD_HUMAN_CHEERING', duration = 2800 },
        { type = 'anim', dict = 'gestures@m@standing@casual', clip = 'gesture_hello', duration = 1800, flag = 48 },
        { type = 'anim', dict = 'gestures@m@standing@casual', clip = 'gesture_nod_yes_hard', duration = 1700, flag = 48 },
        { type = 'anim', dict = 'gestures@m@standing@casual', clip = 'gesture_pleased', duration = 2100, flag = 48 },
        { type = 'anim', dict = 'gestures@m@standing@casual', clip = 'gesture_point', duration = 1700, flag = 48 },
        { type = 'anim', dict = 'amb@world_human_cheering@male_a', clip = 'base', duration = 2400, flag = 49 },
        { type = 'anim', dict = 'rcmnigel1c', clip = 'hailing_whistle_waive_a', duration = 2000, flag = 49 },
        { type = 'anim', dict = 'amb@world_human_cheering@male_a', clip = 'base', duration = 3000, flag = 49 },
        { type = 'anim', dict = 'amb@world_human_cheering@female_a', clip = 'base', duration = 3000, flag = 49 },
        { type = 'anim', dict = 'anim@mp_player_intcelebrationmale@slow_clap', clip = 'slow_clap', duration = 3200, flag = 49 },
        { type = 'anim', dict = 'anim@mp_player_intcelebrationfemale@slow_clap', clip = 'slow_clap', duration = 3200, flag = 49 },
        { type = 'anim', dict = 'amb@world_human_partying@male@partying_beer@base', clip = 'base', duration = 3500, flag = 49 },
        { type = 'anim', dict = 'amb@world_human_partying@female@partying_cellphone@base', clip = 'base', duration = 3500, flag = 49 },
        { type = 'anim', dict = 'random@street_race', clip = 'grid_girl_race_start', duration = 3000, flag = 49 },
        { type = 'anim', dict = 'anim@heists@heist_corona@single_team', clip = 'single_team_loop_boss', duration = 3500, flag = 49 },
        { type = 'anim', dict = 'amb@world_human_hang_out_street@male_b@idle_a', clip = 'idle_a', duration = 3500, flag = 49 },
        { type = 'anim', dict = 'amb@world_human_hang_out_street@female_hold_arm@idle_a', clip = 'idle_a', duration = 3500, flag = 49 },
        { type = 'scenario', name = 'WORLD_HUMAN_SMOKING', duration = 5000 },
        { type = 'scenario', name = 'WORLD_HUMAN_SMOKING_POT', duration = 5000 },
        { type = 'anim', dict = 'anim@amb@nightclub@mini@dance@dance_solo@male@var_b@', clip = 'high_center_down', duration = 2800, flag = 49 },
        { type = 'anim', dict = 'anim@amb@nightclub@mini@dance@dance_solo@male@var_a@', clip = 'high_center', duration = 2800, flag = 49 },
        { type = 'anim', dict = 'anim@amb@nightclub@mini@dance@dance_solo@female@var_a@', clip = 'med_center', duration = 2800, flag = 49 },
        { type = 'scenario', name = 'WORLD_HUMAN_DRINKING', duration = 4000 },
        { type = 'scenario', name = 'WORLD_HUMAN_STAND_IMPATIENT', duration = 3000 },
        { type = 'scenario', name = 'WORLD_HUMAN_STAND_WAITING', duration = 3000 },
        { type = 'anim', dict = 'gestures@m@standing@casual', clip = 'gesture_point', duration = 2000, flag = 48 },
        { type = 'anim', dict = 'gestures@m@standing@casual', clip = 'gesture_bring_it_on', duration = 2200, flag = 48 },
        { type = 'anim', dict = 'rcmnigel1c', clip = 'hailing_whistle_waive_a', duration = 2200, flag = 49 },
        { type = 'anim', dict = 'mp_player_int_uppercheer', clip = 'mp_player_int_cheer', duration = 2500, flag = 49 },
        { type = 'anim', dict = 'amb@world_human_musician@guitar@male@idle_a', clip = 'idle_b', duration = 3500, flag = 49 },
        { type = 'anim', dict = 'amb@world_human_hang_out_street@male_c@idle_a', clip = 'idle_a', duration = 3500, flag = 49 },
        { type = 'anim', dict = 'anim@mp_player_intcelebrationmale@laugh', clip = 'laugh', duration = 2500, flag = 49 },
        { type = 'anim', dict = 'anim@mp_player_intcelebrationfemale@laugh', clip = 'laugh', duration = 2500, flag = 49 },
        { type = 'anim', dict = 'missheistdockssetup1ig_5@idle_a', clip = 'idle_a', duration = 3000, flag = 49 },
        { type = 'anim', dict = 'gestures@m@standing@casual', clip = 'gesture_shrug_hard', duration = 2000, flag = 48 },
        { type = 'anim', dict = 'gestures@m@standing@casual', clip = 'gesture_what', duration = 2000, flag = 48 },
        { type = 'anim', dict = 'rcmnigel1bnmt_1b', clip = 'dance_intro_tyler', duration = 3000, flag = 49 },
        { type = 'anim', dict = 'rcmnigel1bnmt_1b', clip = 'dance_loop_tyler', duration = 3500, flag = 49 },
        { type = 'scenario', name = 'WORLD_HUMAN_STUPOR', duration = 4000 }, 
        { type = 'scenario', name = 'WORLD_HUMAN_STAND_IMPATIENT_UPRIGHT', duration = 3000 },
        { type = 'scenario', name = 'WORLD_HUMAN_STAND_MOBILE_UPRIGHT', duration = 3000 },
        { type = 'anim', dict = 'amb@world_human_cheering@male_a', clip = 'base', duration = 3000, flag = 49 },
        { type = 'anim', dict = 'amb@world_human_cheering@female_a', clip = 'base', duration = 3000, flag = 49 },
        { type = 'anim', dict = 'anim@mp_player_intcelebrationmale@slow_clap', clip = 'slow_clap', duration = 3200, flag = 49 },
        { type = 'anim', dict = 'anim@mp_player_intcelebrationfemale@slow_clap', clip = 'slow_clap', duration = 3200, flag = 49 },
        { type = 'anim', dict = 'anim@mp_player_intcelebrationmale@clap', clip = 'clap', duration = 2500, flag = 49 },
        { type = 'anim', dict = 'anim@mp_player_intcelebrationfemale@clap', clip = 'clap', duration = 2500, flag = 49 },
        { type = 'anim', dict = 'anim@mp_player_intcelebrationmale@cheer', clip = 'cheer', duration = 2500, flag = 49 },
        { type = 'anim', dict = 'anim@amb@nightclub@mini@dance@dance_solo@male@var_b@', clip = 'high_center_down', duration = 3000, flag = 49 },
        { type = 'anim', dict = 'anim@amb@nightclub@mini@dance@dance_solo@male@var_a@', clip = 'high_center', duration = 3000, flag = 49 },
        { type = 'anim', dict = 'anim@amb@nightclub@mini@dance@dance_solo@male@var_c@', clip = 'low_center', duration = 3000, flag = 49 },
        { type = 'anim', dict = 'anim@amb@nightclub@mini@dance@dance_solo@female@var_a@', clip = 'med_center', duration = 3000, flag = 49 },
        { type = 'anim', dict = 'anim@amb@nightclub@mini@dance@dance_solo@female@var_b@', clip = 'low_center', duration = 3000, flag = 49 },
        { type = 'anim', dict = 'anim@amb@nightclub@mini@dance@dance_solo@female@var_c@', clip = 'high_center', duration = 3000, flag = 49 },
        { type = 'anim', dict = 'rcmnigel1bnmt_1b', clip = 'dance_intro_tyler', duration = 2800, flag = 49 },
        { type = 'anim', dict = 'rcmnigel1bnmt_1b', clip = 'dance_loop_tyler', duration = 3000, flag = 49 },
        { type = 'anim', dict = 'amb@world_human_musician@guitar@male@idle_a', clip = 'idle_a', duration = 3500, flag = 49 },
        { type = 'anim', dict = 'amb@world_human_musician@guitar@male@idle_a', clip = 'idle_b', duration = 3500, flag = 49 },
        { type = 'anim', dict = 'amb@world_human_musician@guitar@male@idle_a', clip = 'idle_c', duration = 3500, flag = 49 },
        { type = 'anim', dict = 'amb@world_human_hang_out_street@male_c@idle_a', clip = 'idle_a', duration = 3500, flag = 49 },
        { type = 'anim', dict = 'amb@world_human_hang_out_street@male_c@idle_a', clip = 'idle_b', duration = 3500, flag = 49 },
        { type = 'scenario', name = 'WORLD_HUMAN_SMOKING', duration = 5000 },
        { type = 'scenario', name = 'WORLD_HUMAN_SMOKING_POT', duration = 5000 },
        { type = 'scenario', name = 'WORLD_HUMAN_DRINKING', duration = 4000 },
        { type = 'scenario', name = 'WORLD_HUMAN_HANG_OUT_STREET', duration = 5000 },
        { type = 'anim', dict = 'anim@mp_player_intcelebrationmale@laugh', clip = 'laugh', duration = 2500, flag = 49 },
        { type = 'anim', dict = 'anim@mp_player_intcelebrationfemale@laugh', clip = 'laugh', duration = 2500, flag = 49 },
        { type = 'anim', dict = 'gestures@m@standing@casual', clip = 'gesture_point', duration = 2000, flag = 48 },
        { type = 'anim', dict = 'gestures@m@standing@casual', clip = 'gesture_bring_it_on', duration = 2000, flag = 48 },
        { type = 'anim', dict = 'gestures@m@standing@casual', clip = 'gesture_thumbs_up', duration = 1800, flag = 48 },
        { type = 'anim', dict = 'gestures@m@standing@casual', clip = 'gesture_me', duration = 1800, flag = 48 },
        { type = 'anim', dict = 'mp_player_int_uppercheer', clip = 'mp_player_int_cheer', duration = 2500, flag = 49 },
        { type = 'anim', dict = 'rcmnigel1c', clip = 'hailing_whistle_waive_a', duration = 2200, flag = 49 },
        { type = 'scenario', name = 'WORLD_HUMAN_STAND_IMPATIENT', duration = 2500 },
        { type = 'scenario', name = 'WORLD_HUMAN_STAND_WAITING', duration = 2500 },
        { type = 'scenario', name = 'WORLD_HUMAN_LEANING', duration = 4000 },
        { type = 'anim', dict = 'anim@amb@nightclub@mini@dance@dance_solo@male@var_d@', clip = 'low_center', duration = 3200, flag = 49 },
        { type = 'anim', dict = 'anim@amb@nightclub@mini@dance@dance_solo@female@var_d@', clip = 'med_center', duration = 3200, flag = 49 },
        { type = 'anim', dict = 'anim@amb@nightclub@mini@dance@dance_solo@male@var_e@', clip = 'high_center', duration = 3200, flag = 49 },
        { type = 'anim', dict = 'anim@mp_player_intcelebrationmale@pump_up', clip = 'pump_up', duration = 2500, flag = 49 },
        { type = 'anim', dict = 'anim@mp_player_intcelebrationfemale@pump_up', clip = 'pump_up', duration = 2500, flag = 49 },
        { type = 'anim', dict = 'anim@mp_player_intcelebrationmale@thumbs_up', clip = 'thumbs_up', duration = 2000, flag = 49 },
        { type = 'anim', dict = 'anim@mp_player_intupperthumbs_up', clip = 'idle_a', duration = 2200, flag = 49 },
        { type = 'anim', dict = 'anim@mp_player_intcelebrationmale@nod', clip = 'nod', duration = 2000, flag = 49 },
        { type = 'anim', dict = 'amb@world_human_hang_out_street@male_a@idle_a', clip = 'idle_a', duration = 3500, flag = 49 },
        { type = 'anim', dict = 'amb@world_human_hang_out_street@female_a@idle_a', clip = 'idle_a', duration = 3500, flag = 49 },
        { type = 'scenario', name = 'WORLD_HUMAN_PARTYING', duration = 4500 },
        { type = 'scenario', name = 'WORLD_HUMAN_STUPOR', duration = 4500 },
        { type = 'anim', dict = 'move_m@drunk@slightlydrunk', clip = 'idle', duration = 3000, flag = 49 },
        { type = 'anim', dict = 'anim@mp_player_intcelebrationmale@rock', clip = 'rock', duration = 2500, flag = 49 },
        { type = 'anim', dict = 'anim@mp_player_intcelebrationmale@salute', clip = 'salute', duration = 2000, flag = 49 },
        { type = 'scenario', name = 'WORLD_HUMAN_GUARD_STAND', duration = 4000 },
        { type = 'scenario', name = 'WORLD_HUMAN_STAND_FIRE', duration = 3500 },
        { type = 'anim', dict = 'gestures@m@standing@casual', clip = 'gesture_easy_now', duration = 1800, flag = 48 },
        { type = 'anim', dict = 'gestures@m@standing@casual', clip = 'gesture_no_way', duration = 1800, flag = 48 },
        { type = 'anim', dict = 'gestures@m@standing@casual', clip = 'gesture_damn', duration = 1800, flag = 48 },
        { type = 'anim', dict = 'anim@arena@celeb@flat@solo@no_props@', clip = 'flip_a_player_a', duration = 2000, flag = 49 },
        { type = 'anim', dict = 'missfbi3_sniping', clip = 'dance_m_default', duration = 3000, flag = 49 },
        { type = 'anim', dict = 'special_ped@zombie@monologue_1@monologue_1f', clip = 'iamtheundead_6', duration = 3000, flag = 49 },
        { type = 'anim', dict = 'misscarsteal4@actor', clip = 'actor_berating_loop', duration = 3000, flag = 49 },
        { type = 'anim', dict = 'rcmme_amanda1', clip = 'stand_loop_cop', duration = 3000, flag = 49 },
        { type = 'anim', dict = 'random@drunk_driver_1', clip = 'drunk_fall_over', duration = 2500, flag = 49 },
        { type = 'scenario', name = 'WORLD_HUMAN_STUPOR', duration = 5000 },
        { type = 'anim', dict = 'missheist_agency2aig_13', clip = 'kneel_loop', duration = 3000, flag = 49 },
        { type = 'anim', dict = 'anim@mp_player_intcelebrationmale@face_palm', clip = 'face_palm', duration = 2500, flag = 49 },
        { type = 'anim', dict = 'anim@mp_player_intcelebrationmale@crying', clip = 'crying', duration = 3000, flag = 49 },
        { type = 'scenario', name = 'WORLD_HUMAN_HUMAN_STATUE', duration = 4000 },
        { type = 'anim', dict = 'move_m@quick', clip = 'run', duration = 2000, flag = 49 },
-------------
        { type = 'anim', dict = 'anim@mp_player_intcelebrationmale@rock', clip = 'rock', duration = 3000, flag = 49 },
        { type = 'anim', dict = 'anim@amb@nightclub@mini@dance@dance_solo@male@var_f@', clip = 'high_center', duration = 3200, flag = 49 },
        { type = 'anim', dict = 'anim@amb@nightclub@mini@dance@dance_solo@male@var_g@', clip = 'high_center', duration = 3200, flag = 49 },
        { type = 'anim', dict = 'anim@amb@nightclub@mini@dance@dance_solo@male@var_h@', clip = 'low_center', duration = 3200, flag = 49 },
        { type = 'anim', dict = 'anim@amb@nightclub@mini@dance@dance_solo@female@var_e@', clip = 'med_center', duration = 3200, flag = 49 },
        { type = 'anim', dict = 'anim@amb@nightclub@mini@dance@dance_solo@female@var_f@', clip = 'low_center', duration = 3200, flag = 49 },
        { type = 'anim', dict = 'anim@amb@nightclub@mini@dance@dance_solo@female@var_g@', clip = 'high_center', duration = 3200, flag = 49 },
        { type = 'anim', dict = 'anim@amb@nightclub@dancers@club_ambientpeds@', clip = 'mi_dance_facedj_17_v1_female^1', duration = 4000, flag = 49 },
        { type = 'anim', dict = 'anim@amb@nightclub@dancers@club_ambientpeds@', clip = 'mi_dance_facedj_15_v2_male^1', duration = 4000, flag = 49 },
        { type = 'anim', dict = 'anim@amb@nightclub@dancers@club_ambientpeds@', clip = 'mi_dance_facedj_13_v1_male^1', duration = 4000, flag = 49 },
        { type = 'anim', dict = 'anim@amb@nightclub@mini@dance@dance_solo@male@var_a@', clip = 'low_center', duration = 3000, flag = 49 },
        { type = 'anim', dict = 'anim@amb@nightclub@mini@dance@dance_solo@female@var_a@', clip = 'high_center', duration = 3000, flag = 49 },
        { type = 'anim', dict = 'anim@mp_player_intcelebrationmale@dance', clip = 'dance', duration = 2800, flag = 49 },
        { type = 'anim', dict = 'anim@mp_player_intcelebrationfemale@dance', clip = 'dance', duration = 2800, flag = 49 },
        { type = 'anim', dict = 'anim@amb@nightclub@peds@', clip = 'rcmme_amanda1_stand_loop_cop', duration = 3500, flag = 49 },
        { type = 'anim', dict = 'misschinese2_crystalmazemcs1_cs', clip = 'dance_loop_tao', duration = 3000, flag = 49 },
        { type = 'anim', dict = 'missfbi3_sniping', clip = 'dance_m_default', duration = 3000, flag = 49 },
        { type = 'anim', dict = 'special_ped@mountainlion@monologue_3@monologue_3a', clip = 'idle', duration = 3000, flag = 49 },
        { type = 'anim', dict = 'anim@amb@nightclub@mini@dance@dance_solo@male@var_b@', clip = 'low_center', duration = 3200, flag = 49 },
        { type = 'anim', dict = 'anim@amb@nightclub@mini@dance@dance_solo@male@var_c@', clip = 'high_center', duration = 3200, flag = 49 },
        { type = 'anim', dict = 'anim@amb@nightclub@mini@dance@dance_solo@male@var_d@', clip = 'high_center', duration = 3200, flag = 49 },
        { type = 'anim', dict = 'anim@amb@nightclub@mini@dance@dance_solo@female@var_b@', clip = 'high_center', duration = 3200, flag = 49 },
        { type = 'anim', dict = 'anim@amb@nightclub@mini@dance@dance_solo@female@var_c@', clip = 'med_center', duration = 3200, flag = 49 },
        { type = 'anim', dict = 'anim@amb@nightclub@dancers@crowddance_facedj@', clip = 'hi_dance_facedj_09_v2_male^5', duration = 4000, flag = 49 },
        { type = 'anim', dict = 'anim@amb@nightclub@dancers@crowddance_facedj@', clip = 'hi_dance_facedj_09_v2_female^5', duration = 4000, flag = 49 },
        { type = 'anim', dict = 'anim@amb@nightclub@dancers@crowddance_facedj@', clip = 'hi_dance_facedj_11_v1_male^5', duration = 4000, flag = 49 },
        { type = 'anim', dict = 'anim@amb@nightclub@dancers@crowddance_groups@hi_intensity', clip = 'hi_dance_crowd_09_v1_male^6', duration = 4000, flag = 49 },
        { type = 'anim', dict = 'anim@amb@nightclub@dancers@crowddance_groups@med_intensity', clip = 'med_dance_crowd_09_v2_female^1', duration = 4000, flag = 49 },
        { type = 'anim', dict = 'anim@mp_player_intcelebrationmale@jumping_jacks', clip = 'jumping_jacks', duration = 2500, flag = 49 },
        { type = 'anim', dict = 'anim@mp_player_intcelebrationfemale@jumping_jacks', clip = 'jumping_jacks', duration = 2500, flag = 49 },
        { type = 'anim', dict = 'anim@mp_player_intcelebrationmale@wave', clip = 'wave', duration = 2500, flag = 49 },
        { type = 'anim', dict = 'anim@mp_player_intcelebrationfemale@wave', clip = 'wave', duration = 2500, flag = 49 },
        { type = 'anim', dict = 'rcmfanatic1celebrate', clip = 'celebrate', duration = 3000, flag = 49 },
        { type = 'anim', dict = 'rcmfanatic1celebrate', clip = 'celebrate_male', duration = 3000, flag = 49 },
        { type = 'anim', dict = 'missfam4', clip = 'base', duration = 3000, flag = 49 },
        { type = 'scenario', name = 'WORLD_HUMAN_PARTYING', duration = 5000 },
    },

    tipReaction = {
        enabled = true,
        dict = 'mp_common',
        clip = 'givetake1_a',
        duration = 1500,
        flag = 48,
        speech = 'GENERIC_THANKS'
    }
}

Config.Payouts = {
    cashType = 'cash',
    minTip = 1,
    maxTip = 6,
    cooldownMs = 2500,
    maxTipsPerSession = 100,
    maxSessionEarnings = 1000
}
